// Mocks generated by Mockito 5.4.6 from annotations
// in chatting_app/test/Futures/chat/presentation/bloc/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chatting_app/core/error/failure.dart' as _i6;
import 'package:chatting_app/core/usecase/usecase.dart' as _i12;
import 'package:chatting_app/Futures/chat/domain/entity/chat_entity.dart'
    as _i11;
import 'package:chatting_app/Futures/chat/domain/entity/message_entity.dart'
    as _i8;
import 'package:chatting_app/Futures/chat/domain/repositories/chat_repository.dart'
    as _i2;
import 'package:chatting_app/Futures/chat/domain/usecase/delete_chat_usecase.dart'
    as _i4;
import 'package:chatting_app/Futures/chat/domain/usecase/get_chat_usecase.dart'
    as _i13;
import 'package:chatting_app/Futures/chat/domain/usecase/get_messages_usecase.dart'
    as _i9;
import 'package:chatting_app/Futures/chat/domain/usecase/initiate_chat_usecase.dart'
    as _i10;
import 'package:chatting_app/Futures/chat/domain/usecase/send_message_usecase.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatRepository_0 extends _i1.SmartFake
    implements _i2.ChatRepository {
  _FakeChatRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeleteChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteChatUseCase extends _i1.Mock implements _i4.DeleteChatUseCase {
  MockDeleteChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [chatId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [chatId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i7.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.MessageEntity>> call(
    _i8.MessageEntity? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [message]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i8.MessageEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i8.MessageEntity>(
                    this,
                    Invocation.method(#call, [message]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.MessageEntity>>);
}

/// A class which mocks [GetMessagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessagesUseCase extends _i1.Mock
    implements _i9.GetMessagesUseCase {
  MockGetMessagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.MessageEntity>>> call(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [chatId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i8.MessageEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i8.MessageEntity>>(
                    this,
                    Invocation.method(#call, [chatId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i8.MessageEntity>>>);
}

/// A class which mocks [InitiateChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitiateChatUseCase extends _i1.Mock
    implements _i10.InitiateChatUseCase {
  MockInitiateChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>> call(
    _i12.ChatParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i11.ChatEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>>);
}

/// A class which mocks [GetChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChatUseCase extends _i1.Mock implements _i13.GetChatUseCase {
  MockGetChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>> call(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [chatId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i11.ChatEntity>(
                    this,
                    Invocation.method(#call, [chatId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i11.ChatEntity>>);
}
